name: Deploy to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-filecapsa-main
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64, core-filecapsa]

    steps:
      - uses: actions/checkout@v4

      - name: Generate .env file
        uses: horlakz/secretenv@v1
        with:
          secrets_json: ${{ toJSON(secrets) }}

      - name: Build Docker image
        run: docker build . -t filecapsa:${{ github.sha }}

  run:
    runs-on: self-hosted
    needs:
      - build

    steps:
      - name: Remove old container
        run: |
          if [ "$(docker ps -aq -f name=^filecapsa$)" ]; then
            docker rm --force filecapsa
          fi

      - name: Run new container
        run: |
          docker run -d \
            --restart unless-stopped \
            --name filecapsa \
            --network knobuk-net \
            --env-file .env \
            -p 8100:${{ secrets.PORT }} \
            filecapsa:${{ github.sha }}
